# Copyright (c) 2019 Patrick Diehl
#               
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

version: 2
jobs:
    build:
        docker:
            - image: fedora:30
        steps:
            - checkout
            - run:
                name: Build
                command: |
                  mkdir build 
                  cd build  
                  cmake ..
                  make
