# Copyright (c) 2019 Patrick Diehl
#               
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

version: 2
jobs:
    build:
        docker:
            - image: fedora:30
        steps:
            - checkout
            - run:
                name: Update
                command: sudo dnf update -y 
            - run:
                name: Install
                command: sudo dnf install make automake cmake g++ blaze-devel -y
            - run:
                name: Build
                command: |
                  mkdir build 
                  cd build  
                  cmake -DBUILD_TESTS=ON ..
                  make
                  make test
